list_markets = [
    'japan', 'portugal', 'russia', 'switzerland', 'romania', 'italy',
    'ukraine', 'germany', 'monaco', 'denmark', 'netherlands', 'greece',
    'spain', 'uk', 'israel', 'new-zealand', 'kazakhstan', 'canada',
    'south-africa', 'lithuania', 'colombia', 'poland', 'turkish-cyprus',
    'france', 'czech-republic', 'korea', 'slovak-republic', 'guatemala',
    'slovenia', 'palestine', 'bulgaria', 'andorra', 'croatia',
    'dominican-republic', 'latvia', 'armenia'
]

dict_pmiMarket_to_ISO = {
     'Andorra': 'AD',
     'Armenia': 'AM',
     'Bulgaria': 'BG',
     'Canada': 'CA',
     'Switzerland': 'CH',
     'Colombia': 'CO',
     'Curacao': 'CW',
     'Turkish Cyprus': 'CY',
     'Cyprus': 'CY',
     'Czech Republic': 'CZ',
     'Germany': 'DE',
     'Denmark': 'DK',
     'Dominican Republic': 'DO',
     'Spain': 'ES',
     'France': 'FR',
     'UK': 'GB',
     'Greece': 'GR',
     'Guatemala': 'GT',
     'Croatia': 'HR',
     'Israel': 'IL',
     'Italy': 'IT',
     'Japan': 'JP',
     'Korea': 'KR',
     'Kazakhstan': 'KZ',
     'Lithuania': 'LT',
     'Latvia': 'LV',
     'Monaco': 'MC',
     'Netherlands': 'NL',
     'New Zealand': 'NZ',
     'Poland': 'PL',
     'Palestine': 'PS',
     'Portugal': 'PT',
     'Romania': 'RO',
     'Serbia': 'RS',
     'Russia': 'RU',
     'Slovenia': 'SI',
     'Slovak Republic': 'SK',
     'Ukraine': 'UA',
     'South Africa': 'ZA'
}
